workflows:
  android-debug:
    name: Android Debug Build

    environment:
      node: 22

    scripts:
      - npm install --legacy-peer-deps
      - npm run build
      - npx cap add android || true
      - npx cap sync android

      - name: Debug
        script: |
          ls
          ls android
          
      - name: Build Android
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk