// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-events.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_events_default = defineTool({
  name: "list_events",
  title: "Listar eventos",
  description: "Lista os eventos (datas importantes) do usu\xE1rio autenticado, opcionalmente filtrando por categoria ou favoritos.",
  inputSchema: {
    category: z.string().optional().describe("Filtro opcional pela categoria exata do evento."),
    onlyFavorites: z.boolean().optional().describe("Se true, retorna somente eventos marcados como favoritos."),
    limit: z.number().int().min(1).max(200).optional().describe("M\xE1ximo de eventos a retornar (padr\xE3o 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, onlyFavorites, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("events").select("id, label, category, date, recurring, favorite").eq("user_id", ctx.getUserId()).order("date", { ascending: true }).limit(limit ?? 100);
    if (category) query = query.eq("category", category);
    if (onlyFavorites) query = query.eq("favorite", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-event.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_event_default = defineTool2({
  name: "create_event",
  title: "Criar evento",
  description: "Cria uma nova data/evento para o usu\xE1rio autenticado no app Quanto Tempo?",
  inputSchema: {
    label: z2.string().trim().min(1).max(200).describe("Nome/descri\xE7\xE3o do evento."),
    category: z2.string().trim().min(1).max(120).describe("Categoria do evento (ex.: 'Anivers\xE1rio de casamento')."),
    date: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Formato esperado: YYYY-MM-DD").describe("Data do evento no formato ISO (YYYY-MM-DD)."),
    recurring: z2.boolean().optional().describe("Se o evento se repete anualmente."),
    favorite: z2.boolean().optional().describe("Marcar como favorito.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ label, category, date, recurring, favorite }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("events").insert({
      user_id: ctx.getUserId(),
      label,
      category,
      date,
      recurring: recurring ?? false,
      favorite: favorite ?? false
    }).select("id, label, category, date, recurring, favorite").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { event: data }
    };
  }
});

// src/lib/mcp/tools/delete-event.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var delete_event_default = defineTool3({
  name: "delete_event",
  title: "Excluir evento",
  description: "Exclui permanentemente um evento do usu\xE1rio autenticado. Requer confirma\xE7\xE3o por ser irrevers\xEDvel.",
  inputSchema: {
    id: z3.string().uuid().describe("Identificador do evento a excluir.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { error } = await supabaseForUser3(ctx).from("events").delete().eq("id", id).eq("user_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Evento ${id} exclu\xEDdo.` }] };
  }
});

// src/lib/mcp/tools/list-lists.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.100.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_lists_default = defineTool4({
  name: "list_lists",
  title: "Listar listas compartilhadas",
  description: "Retorna as listas que o usu\xE1rio autenticado criou ou participa como membro.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("lists").select("id, name, owner_id, created_at").order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { lists: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/time-since.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function parseLocalDate(dateStr) {
  const [y, m, d] = dateStr.slice(0, 10).split("-").map(Number);
  return new Date(y, (m ?? 1) - 1, d ?? 1);
}
function diff(a, b) {
  const [earlier, later] = a > b ? [b, a] : [a, b];
  let years = later.getFullYear() - earlier.getFullYear();
  let months = later.getMonth() - earlier.getMonth();
  let days = later.getDate() - earlier.getDate();
  if (days < 0) {
    months--;
    const prev = new Date(later.getFullYear(), later.getMonth(), 0);
    days += prev.getDate();
  }
  if (months < 0) {
    years--;
    months += 12;
  }
  return { years, months, days };
}
var time_since_default = defineTool5({
  name: "time_since",
  title: "Calcular tempo desde/at\xE9 uma data",
  description: "Calcula o tempo decorrido ou faltante (anos, meses, dias e total de dias) entre hoje e uma data informada.",
  inputSchema: {
    date: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Formato esperado: YYYY-MM-DD").describe("Data no formato YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ date }) => {
    const target = parseLocalDate(date);
    const now = /* @__PURE__ */ new Date();
    const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const isFuture = target.getTime() > today.getTime();
    const parts = diff(target, today);
    const totalDays = Math.round(Math.abs(target.getTime() - today.getTime()) / 864e5);
    const result = { direction: isFuture ? "future" : "past", ...parts, totalDays };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qhqhyjpqgrvrxjiosoha";
var mcp_default = defineMcp({
  name: "quanto-tempo-mcp",
  title: "Quanto tempo? MCP",
  version: "0.1.0",
  instructions: "Ferramentas do app Quanto Tempo?: liste, crie e exclua datas importantes (anivers\xE1rios, marcos, etc.) e calcule o tempo decorrido/faltante para qualquer data. Todas as a\xE7\xF5es operam sobre a conta do usu\xE1rio conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_events_default, create_event_default, delete_event_default, list_lists_default, time_since_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
